name = "ipogyani"
type = "service"
main = ".open-next/worker.js"
compatibility_date = "2024-04-15"

[build]
command = "pnpm run build"
cwd = "./"
watch_paths = ["./app/**/*.ts", "./app/**/*.tsx", "./components/**/*.ts", "./components/**/*.tsx"]

[build.upload]
format = "modules"
main = ".open-next/worker.js"

[env.production]
name = "ipogyani-prod"
vars = { ENVIRONMENT = "production" }

[[observability.enabled]]
enabled = true
