-- =============================================
-- Admin Authentication Table
-- =============================================

-- Drop existing table if any
DROP TABLE IF EXISTS admins CASCADE;

-- Create admins table
CREATE TABLE admins (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  must_reset_password BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes
CREATE INDEX idx_admins_username ON admins(username);

-- Create updated_at trigger
CREATE TRIGGER update_admins_updated_at
  BEFORE UPDATE ON admins
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Enable RLS
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;

-- RLS Policies - Service role (backend) has full access
CREATE POLICY "Service role full access" ON admins FOR ALL USING (true) WITH CHECK (true);

-- =============================================
-- Seed: Create default admin user
-- Username: admin
-- Password: changeme123 (bcrypt hash with salt)
-- Hash generated by bcrypt with salt rounds: 10
-- =============================================

-- Insert default admin (you can run this separately or include in your seed script)
-- The hash below is a REAL bcrypt hash of "changeme123" (cost 10) - verified.
-- Previous revision of this file shipped a placeholder hash that silently
-- failed verifyPassword(), causing "Invalid credentials" even with the right
-- password. Keep this value in sync with scripts/seed-admin.ts if you rotate it.
INSERT INTO admins (username, password_hash, must_reset_password)
VALUES (
  'admin',
  '$2b$10$x1RYd7tiTD7q0xjfqLD0BOb9HeS2GhD3MB4cYk9chWABU281LnQpe',
  true
)
ON CONFLICT (username) DO UPDATE
SET password_hash       = EXCLUDED.password_hash,
    must_reset_password = true,
    updated_at          = NOW();
