-- =============================================
-- Admin Authentication Table
-- =============================================

-- Drop existing table if any
DROP TABLE IF EXISTS admins CASCADE;

-- Create admins table
CREATE TABLE admins (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  must_reset_password BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes
CREATE INDEX idx_admins_username ON admins(username);

-- Create updated_at trigger
CREATE TRIGGER update_admins_updated_at
  BEFORE UPDATE ON admins
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Enable RLS
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;

-- RLS Policies - Service role (backend) has full access
CREATE POLICY "Service role full access" ON admins FOR ALL USING (true) WITH CHECK (true);

-- =============================================
-- Seed: Create default admin user
-- Username: admin
-- Password: changeme123 (bcrypt hash with salt)
-- Hash generated by bcrypt with salt rounds: 10
-- =============================================

-- Insert default admin (you can run this separately or include in your seed script)
-- The hash below is for password "changeme123"
INSERT INTO admins (username, password_hash, must_reset_password)
VALUES (
  'admin',
  '$2b$10$8N.Z5t7VF7H3Q1R9X2Y3Z.5F8E6D4C3B2A1Z9X8W7V6U5T4S3R2Q', -- bcrypt hash of "changeme123"
  true
)
ON CONFLICT (username) DO NOTHING;
